sudo: required
language: python
python:
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.9"
#    - "3.10"  # TODO: uncomment when supported by travis
    - "flake8"
    - "coverage"
install:
    - pip install tox-travis
services: docker
script:
    - tox
